config/routes.rb
Lox::Application.routes.draw do
  resources :venues

  resources :countries

  resources :regions

  resources :cities

end

app/models/venue.rb
class Venue < ActiveRecord::Base
  belongs_to :city
  belongs_to :region
  belongs_to :country

  geocoded_by :full_location

  before_validation :geocode
  before_save :add_to_location

  attr_accessor :location

  def location
    loc = []
    loc << city.name if city.present?
    loc << region.name if region.present?
    loc << country.name if country.present?
    loc.join(", ")
  end

private

  def full_location
    logger.debug "Geocoding #{self.street_address}, #{@location}"
    "#{self.street_address}, #{@location}"
  end

  def add_to_location
    loc = @location.split(", ")
    logger.debug loc
    
    reg = Region.find_or_create_by_name(loc[1])
    cnt = Country.find_or_create_by_name(loc[2])
    cit = City.find_or_create_by_name_and_region_id_and_country_id(loc[0], reg.id, cnt.id)

    reg.cities << cit
    cnt.regions << reg

    self.region_id = reg.id
    self.country_id = cnt.id
    self.city_id = cit.id
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @venues }
    end
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
    @venue = Venue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @venue }
    end
  end

  # GET /venues/new
  # GET /venues/new.json
  def new
    @venue = Venue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @venue }
    end
  end

  # GET /venues/1/edit
  def edit
    @venue = Venue.find(params[:id])
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.new(params[:venue])

    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: 'Venue was successfully created.' }
        format.json { render json: @venue, status: :created, location: @venue }
      else
        format.html { render action: "new" }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /venues/1
  # PUT /venues/1.json
  def update
    @venue = Venue.find(params[:id])

    respond_to do |format|
      if @venue.update_attributes(params[:venue])
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue = Venue.find(params[:id])
    @venue.destroy

    respond_to do |format|
      format.html { redirect_to venues_url }
      format.json { head :ok }
    end
  end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%= form_for(@venue) do |f| %>
  <% if @venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% @venue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
  <div class="field">
    <%= f.label :street_address %><br />
    <%= f.text_field :street_address %>
  </div>
  <div class="ui-widget">
    <div class="field">
      <%= f.label :location %><br />
      <%= f.text_field :location %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<style>
  .ui-autocomplete-loading { background: white url('<%= asset_path("ui-anim_basic_16x16.gif") %>') right center no-repeat; }
  #venue_location { width: 25em; }
</style> 

<script>
$(function() {
  $( "#venue_location" ).autocomplete({
    source: function( request, response ) {
      $.ajax({
        url: "http://ws.geonames.org/searchJSON",
        dataType: "jsonp",
        data: {
          featureClass: "P",
          style: "full",
          maxRows: 12,
          name_startsWith: request.term
        },
        success: function( data ) {
          response( $.map( data.geonames, function( item ) {
            return {
              label: item.name + (item.adminName1 ? ", " + item.adminName1 : "") + ", " + item.countryName,
              value: item.name
            }
          }));
        }
      });
    },
    minLength: 2,
    focus: function( event, ui ) {
      $( "#venue_location" ).val( ui.item.label );
      return false;
    },
    select: function( event, ui ) {
      $("#venue_location").val(ui.item.label);
      return false;
    },
    open: function() {
      $( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
    },
    close: function() {
      $( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
    }
  });
});
</script>

app/views/venues/edit.html.erb
<h1>Editing venue</h1>

<%= render 'form' %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<h1>Listing venues</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Notes</th>
    <th>Street address</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @venues.each do |venue| %>
  <tr>
    <td><%= venue.name %></td>
    <td><%= venue.notes %></td>
    <td><%= venue.street_address %></td>
    <td><%= venue.city.name if venue.city.present? %></td>
    <td><%= venue.region.name if venue.region.present? %></td>
    <td><%= venue.country.name if venue.country.present? %></td>
    <td><%= venue.latitude.to_s + ", " + venue.longitude.to_s %></td>
    <td><%= link_to 'Show', venue %></td>
    <td><%= link_to 'Edit', edit_venue_path(venue) %></td>
    <td><%= link_to 'Destroy', venue, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Venue', new_venue_path %>

app/views/venues/new.html.erb
<h1>New venue</h1>

<%= render 'form' %>

<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @venue.name %>
</p>

<p>
  <b>Notes:</b>
  <%= @venue.notes %>
</p>

<p>
  <b>Street address:</b>
  <%= @venue.street_address %>
</p>

<p>
  <b>Latitude:</b>
  <%= @venue.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @venue.longitude %>
</p>


<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %>